### ISSUE TITLE
countTo of 1 is running infinitely

### ISSUE THREAD

**Issue by stephenhuey** [arjunmehta/heartbeats#10]
My package.json has heartbeats ^3.1.3 and I'm running Node 6.9.4.  Trying to use countTo to run a function only once on a delay of 2 beats, but it's running infinitely with this: 

createEvent(2, { countTo: 1 }, function (count, last)

Also, when I log count here, it's not the number of times that the function has been run, but rather the age of the heart.  Doesn't seem to be what you intended.

**Comment by arjunmehta** [comment]
@stephenhuey 
Ah yes the API changed. There was a breaking change to the API, please update to the latest 5.x.x release, or refer to the [old docs for 3.1.5](https://github.com/arjunmehta/heartbeats/tree/a4cc954783b8f41436b4b97023c3ee3c1dec336d)

You want to use `{ repeat: 1 }` instead of `{ countTo: 1 }`.

You can continue to use `repeat` with v5.x but the `countTo` keyword didn't exist in 3.x.

**Comment by arjunmehta** [comment]
@stephenhuey[ more info here](https://github.com/arjunmehta/heartbeats/releases/tag/v5.0.1).

**Comment by stephenhuey** [comment]
Thanks, that worked!
