### ISSUE TITLE
Not working in Aurelia

### ISSUE THREAD

**Issue by stephenhuey** [arjunmehta/heartbeats#6]
I've been using heartbeats in server-side node and Angular but I can't get it to work in Aurelia and have identified the issue with the help of their Gitter channel.  The client-side SPA framework Aurelia allows npm modules to be installed, but since node is using RequireJS, the way heartbeats is referencing its files breaks the build.  Here's a bit from the RequireJS documentation:  

//If a colon is in the URL, it indicates a protocol is used and it is just
//an URL to a file, or if it starts with a slash, contains a query arg (i.e. ?)
//or ends with .js, then assume the user meant to use an url and not a module id.

In this particular instance, since Heartbeat is adding .js extensions, it’s assuming that what’s being asked for is not a module, and therefore when it asks for a file via ./, it’s current working directory is actually the root of the application, hence why the route is not correct.  So I believe the solution would be to remove the .js extensions from require statement in main.js and the other files.

**Comment by AStoker** [comment]
Just adding a bit of detail here. The issue isn't in Aurelia, but rather in a library that Aurelia uses to trace dependencies (called AmodroTrace), and that library uses RequireJS to generate a map of needed file paths. Because the require calls inside Heartbeats adds the `.js` extension (unnecessarily from what I can tell), RequireJS begins thinking that what it needs to load up is from a url, not a module. Since it's not going to treat the request as a module request, it loses the correct module path of existing inside the `node_modules` and runs from the root directory of where the tracing is happening (due to the files being called with the `./` prefix).
I've tested it out (briefly), and simply removing the `.js` extensions solve this problem, and should not cause any other problems. As far as I know, you don't ever need to use extensions unless you are doing something specifically with file systems or absolute paths (neither is this case).
